### PR TITLE
Popup window implemented 

### PR DESCRIPTION
**Pull request by diegoh40**
In this activity was implemented a popup window, where I applied concepts about DOM, JS objects, and Bootstrap, with helped my code partner improve our skills about dynamics tools on our front end layout

### CODE REVIEW

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @diegoh40 ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] In your `README` file, kindly update the "Getting Started" section. This should be an example of how you may give instructions on setting up your project locally.

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Well implemented the requirements.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Review by codepantha — CHANGES_REQUESTED** [review]
Hi @diegoh40 👋,

## STATUS: REQUESTED CHANGES ♻️  

Great work on making the changes requested by the previous reviewer 👏 
You are almost there, just a little bit more to go 👍 



### Highlights 🎯 
- Meaningful commit messages ✔️ 
- Descriptive PR ✔️ 
- Linter checks ✔️ 
 
 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As the previous reviewer suggested, please add this line to your README file to show users how to clone your repo 👇 
```
git clone https://github.com/diegoh40/Diego-Portfolio.git
```

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by diegoh40** [comment]
In this change suggested by the code reviewer I added the path to clone my repository in the README.MD file.

**Review by OLIPLICHE — APPROVED** [review]
Hi @diegoh40 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
